version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7.18
    container_name: mysql-lable
    volumes:
    #   - /apps/mysql/mydir:/mydir
    #   - /apps/mysql/datadir:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/my.cnf
    #   # 数据库还原目录 可将需要还原的sql文件放在这里
    #   - /apps/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_DATABASE=public"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
