version: '3'
services:
  mysql:
    platform: linux/amd64
    restart: always
    image: mysql:5.7.34
    container_name: mysql-lable
    volumes:
    #   - /apps/mysql/mydir:/mydir
    #   - /apps/mysql/datadir:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/my.cnf
    #   # 数据库还原目录 可将需要还原的sql文件放在这里
    #   - /apps/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_DATABASE=public"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
  reids:
    platform: linux/amd64
    image: redis:7.0.4
    container_name: redis-lable
    restart: always
    privileged: true
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
    # command: redis-server /etc/redis/redis.conf
    ports:
      - 16379:6379
    environment:
      - REDIS_PASSWORD=1234
      
    # env_file:
    #   - .env.development.local